# Puerto de escucha
http_port 3128

# Directorio de caché
cache_dir ufs /var/spool/squid 100 16 256

# Memoria para caché
cache_mem 256 MB

# Políticas de acceso
acl localnet src 0.0.0.1-255.255.255.255
http_access allow localnet
http_access deny all
