version: '3.8'

volumes:
  nextcloud:
  db:

services:

  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - /opt/mariadbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1qazxsw2
      - MYSQL_PASSWORD=1qazxsw2
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - TZ=America/Caracas
      
  app:
    image: nextcloud:27.1.3-fpm-alpine
    container_name: nextcloudapp
    hostname: nextcloudapp
    restart: always
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
      - /opt/nextclouddata:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=1qazxsw2
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - TZ=America/Caracas
      - NEXTCLOUD_TRUSTED_DOMAINS=nube.cesares.sld.cu
      - VIRTUAL_HOST=nube.cesares.sld.cu
      
  web:
    image: nginx:1.25.3-alpine
    restart: always
    ports:
      - '8080:80'
    links:
      - db
      - app
    volumes:
      - /root/configs/nginx-nextcloudapp/nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - app
    environment:
      - TZ=America/Caracas

  webftp:
    image: avhost/docker-lighttpd:v1.4.73
    container_name: webftp
    hostname: webftp
    restart: always
    ports:
      - '5802:8080'
    volumes:
      - /opt/lighttpd-webftp:/var/www/htdocs 
    environment:
      - TZ=America/Caracas

  webcdm:
    image: avhost/docker-lighttpd:v1.4.73
    container_name: webcdm
    hostname: webcdm
    restart: always
    ports:
      - '5801:8080'
    volumes:
      - /opt/lighttpd-webcdm:/var/www/htdocs
    environment:
      - TZ=America/Caracas
