services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.10.3
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Caracas
      - JELLYFIN_PublishedServerUrl=jellyfin.cesares.sld.cu
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
    volumes:
      - /root/configs/jellyfin:/config
      - /opt/jellyfin/media:/data
    restart: unless-stopped    
