services:
  jellyfin:
    image: linuxserver/jellyfin:10.10.3
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Havana
      # - JELLYFIN_PublishedServerUrl=jellyfin.mydomain.cu
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
    volumes:
      - /opt/jellyfin-config:/config
      - /opt/jellyfin-media:/data
    restart: unless-stopped    
