version: "3.1"

networks:
  nextcloudnet:
  
services:
  nextcloudbd:
    image: mariadb:10.6
    container_name: nextcloudbd
    hostname: nextcloudbd
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - /opt/nextcloudbd:/var/lib/mysql
    networks:
      - nextcloudnet
    environment:
      - MYSQL_ROOT_PASSWORD=1qazxsw2
      - MYSQL_PASSWORD=1qazxsw2
      - MYSQL_DATABASE=nextcloudbd
      - MYSQL_USER=nextcloudbd
      - TZ=America/Havana
  nextcloudapp:
    image: nextcloud:27.1.3-fpm-alpine
    container_name: nextcloudapp
    hostname: nextcloudapp
    restart: always
    links:
      - nextcloudbd
    depends_on:
      - nextcloudbd
    volumes:
      - /opt/nextcloudapp:/var/www/html
      - /opt/nextclouddata:/var/www/html/data
    networks:
      - nextcloudnet
    environment:
      - MYSQL_PASSWORD=1qazxsw2
      - MYSQL_DATABASE=nextcloudbd
      - MYSQL_USER=nextcloudbd
      - MYSQL_HOST=nextcloudbd
      - TZ=America/Havana      
  nextcloudwebproxy:
    image: nginx:1.25.3-alpine
    container_name: nextcloudwebproxy
    hostname: nextcloudwebproxy
    restart: always
    ports:
      - 8080:80
    links:
      - nextcloudapp
    depends_on:
      - nextcloudapp
    volumes:
      - /opt/nginx-netcloud-config/nginx-nextcloud.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - nextcloudapp
    networks:
      - nextcloudnet
    environment:
      - TZ=America/Havana
