services:
  moodlebd:
    image: bitnami/mariadb:11.4.4
    container_name: moodlebd
    hostname: moodlebd
    restart: always
    env_file:
      - moodle-moodledb.env
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  moodleapp:
    image: bitnami/moodle:4.5
    container_name: moodleapp
    hostname: moodleapp
    restart: always
    ports:
      - '80:8080'
      - '443:8443'
    env_file:
      - moodle-moodleapp.env
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - moodlebd

volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
