services:

  wordpressdb:
    image: docker.io/bitnami/mariadb:10.6
    container_name: wordpressdb
    volumes:
      - /opt/mariadb_data:/bitnami/mariadb
    environment:
      - wordpressdb.env

  wordpress:
    image: docker.io/bitnami/wordpress-nginx:6
    container_name: wordpress
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - /opt/wordpress_data:/bitnami/wordpress
    depends_on:
      - wordpressdb
    links:
      - wordpressdb
    environment:
      - wordpressapp.env
